{"sections":[],"abstract":[{"text":"Error in internal application.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Logic error, bug, or issue with internal operation, …"}],"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"s:13SwiftErrorKit06SourceB9AttributeO8internalyA2CmF","modules":[{"name":"SwiftErrorKit"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"}],"title":"SourceErrorAttribute.internal","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"`internal`","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/internal"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal","interfaceLanguage":"swift"},"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"kind":"symbol","role":"collection","title":"SwiftErrorKit","url":"\/documentation\/swifterrorkit","abstract":[{"type":"text","text":"Error attribution and commons."}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","type":"topic"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/internal":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"}],"role":"symbol","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/internal","kind":"symbol","abstract":[{"type":"text","text":"Error in internal application."},{"text":" ","type":"text"},{"type":"text","text":"Logic error, bug, or issue with internal operation, …"}],"type":"topic","title":"SourceErrorAttribute.internal","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"title":"SourceErrorAttribute","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"text":" ","type":"text"},{"type":"text","text":"in which the error emerged."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceErrorAttribute"}],"navigatorTitle":[{"text":"SourceErrorAttribute","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","url":"\/documentation\/swifterrorkit\/sourceerrorattribute"}}}