{"metadata":{"roleHeading":"Case","modules":[{"name":"SwiftErrorKit"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"io"}],"externalID":"s:13SwiftErrorKit06SourceB9AttributeO2ioyA2CmF","symbolKind":"case","title":"SourceErrorAttribute.io"},"sections":[],"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"io","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/io"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"abstract":[{"type":"text","text":"Communication error."},{"type":"text","text":" "},{"type":"text","text":"Network outage, connectivity problem, protocol error, …"}],"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute","abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"type":"text","text":" "},{"text":"in which the error emerged.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceErrorAttribute"}],"title":"SourceErrorAttribute","role":"symbol"},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"title":"SwiftErrorKit","url":"\/documentation\/swifterrorkit","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","kind":"symbol","abstract":[{"text":"Error attribution and commons.","type":"text"}],"role":"collection"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/io":{"title":"SourceErrorAttribute.io","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/io","role":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"io","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Communication error."},{"type":"text","text":" "},{"type":"text","text":"Network outage, connectivity problem, protocol error, …"}]}}}