{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"io","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/io"]}],"abstract":[{"type":"text","text":"Communication error."},{"text":" ","type":"text"},{"text":"Network outage, connectivity problem, protocol error, …","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io"},"kind":"symbol","metadata":{"modules":[{"name":"SwiftErrorKit"}],"externalID":"s:13SwiftErrorKit06SourceB9AttributeO2ioyA2CmF","title":"SourceErrorAttribute.io","roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"io"}]},"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"title":"SwiftErrorKit","abstract":[{"text":"Error attribution and commons.","type":"text"}],"kind":"symbol","url":"\/documentation\/swifterrorkit","type":"topic","role":"collection","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"role":"symbol","abstract":[{"text":"An error attribute to include information about the high-level component","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in which the error emerged."}],"type":"topic","title":"SourceErrorAttribute","url":"\/documentation\/swifterrorkit\/sourceerrorattribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/io":{"title":"SourceErrorAttribute.io","type":"topic","role":"symbol","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/io","kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io","abstract":[{"type":"text","text":"Communication error."},{"text":" ","type":"text"},{"type":"text","text":"Network outage, connectivity problem, protocol error, …"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"io","kind":"identifier"}]}}}