{"abstract":[{"text":"Error caused by a system that the process runs on.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Hardware failure, OS-level error, resource exhaustion,"},{"text":" ","type":"text"},{"type":"text","text":"environment configuration, …"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"system"}],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute\/system"]}],"sections":[],"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/system","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"SourceErrorAttribute.system","modules":[{"name":"SwiftErrorKit"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","externalID":"s:13SwiftErrorKit06SourceB9AttributeO6systemyA2CmF","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"system"}]},"kind":"symbol","references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/system":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/system","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"system"}],"title":"SourceErrorAttribute.system","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Error caused by a system that the process runs on."},{"type":"text","text":" "},{"type":"text","text":"Hardware failure, OS-level error, resource exhaustion,"},{"type":"text","text":" "},{"text":"environment configuration, …","type":"text"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/system"},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","title":"SwiftErrorKit","role":"collection","abstract":[{"type":"text","text":"Error attribution and commons."}],"url":"\/documentation\/swifterrorkit"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"navigatorTitle":[{"kind":"identifier","text":"SourceErrorAttribute"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"An error attribute to include information about the high-level component","type":"text"},{"text":" ","type":"text"},{"text":"in which the error emerged.","type":"text"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceErrorAttribute"}],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute","title":"SourceErrorAttribute"}}}