{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute\/typeDescription"},"metadata":{"modules":[{"name":"SwiftErrorKit"}],"title":"typeDescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"typeDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property","externalID":"s:13SwiftErrorKit05TraceB9AttributeV15typeDescriptionSSvp","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"typeDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/swifterrorkit\/traceerrorattribute\/typedescription"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"ErrorAttribute.typeDescription","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit/TraceErrorAttribute":{"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute","url":"\/documentation\/swifterrorkit\/traceerrorattribute","navigatorTitle":[{"text":"TraceErrorAttribute","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TraceErrorAttribute","kind":"identifier"}],"abstract":[{"text":"An error attribute to track a source location.","type":"text"}],"title":"TraceErrorAttribute","role":"symbol","kind":"symbol"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/TraceErrorAttribute/typeDescription":{"url":"\/documentation\/swifterrorkit\/traceerrorattribute\/typedescription","title":"typeDescription","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute\/typeDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"typeDescription"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol"},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"title":"SwiftErrorKit","abstract":[{"text":"Error attribution and commons.","type":"text"}],"kind":"symbol","url":"\/documentation\/swifterrorkit","type":"topic","role":"collection","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit"}}}