{"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"ErrorAttribute.typeDescription"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"typeDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","externalID":"s:13SwiftErrorKit05TraceB9AttributeV15typeDescriptionSSvp","role":"symbol","symbolKind":"property","title":"typeDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"typeDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"SwiftErrorKit"}]},"sections":[],"variants":[{"paths":["\/documentation\/swifterrorkit\/traceerrorattribute\/typedescription"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute\/typeDescription","interfaceLanguage":"swift"},"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","abstract":[{"type":"text","text":"Error attribution and commons."}],"type":"topic","title":"SwiftErrorKit","kind":"symbol","role":"collection","url":"\/documentation\/swifterrorkit"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/TraceErrorAttribute/typeDescription":{"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute\/typeDescription","url":"\/documentation\/swifterrorkit\/traceerrorattribute\/typedescription","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"typeDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","kind":"symbol","title":"typeDescription"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/TraceErrorAttribute":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TraceErrorAttribute"}],"abstract":[{"type":"text","text":"An error attribute to track a source location."}],"title":"TraceErrorAttribute","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute","navigatorTitle":[{"kind":"identifier","text":"TraceErrorAttribute"}],"kind":"symbol","url":"\/documentation\/swifterrorkit\/traceerrorattribute","role":"symbol"}}}