{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit"]]},"abstract":[{"text":"An error attribute to include information about the high-level component","type":"text"},{"type":"text","text":" "},{"text":"in which the error emerged.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"s:13SwiftErrorKit06SourceB9AttributeO","symbolKind":"enum","navigatorTitle":[{"text":"SourceErrorAttribute","kind":"identifier"}],"modules":[{"name":"SwiftErrorKit"}],"roleHeading":"Enumeration","role":"symbol","title":"SourceErrorAttribute","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}]},"seeAlsoSections":[{"generated":true,"title":"Error attributes in the package","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/DebugInfoErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/LocalizationErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/RankErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SeverityErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TagErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/UserLevelErrorAttribute"]}],"topicSections":[{"identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/input","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/system"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/typeDescription","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/valueDescription"],"title":"Instance Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/Equatable-Implementations","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/ErrorAttribute-Implementations","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swifterrorkit\/sourceerrorattribute"]}],"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/ErrorAttribute","doc:\/\/SwiftErrorKit\/SQ","doc:\/\/SwiftErrorKit\/SH","doc:\/\/SwiftErrorKit\/SY"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceErrorAttribute"}]}],"kind":"declarations"}],"references":{"doc://SwiftErrorKit/SY":{"identifier":"doc:\/\/SwiftErrorKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/io":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Communication error."},{"text":" ","type":"text"},{"type":"text","text":"Network outage, connectivity problem, protocol error, …"}],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/io","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/io","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"io"}],"title":"SourceErrorAttribute.io"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/ErrorAttribute-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/errorattribute-implementations","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/ErrorAttribute-Implementations","kind":"article","title":"ErrorAttribute Implementations"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/system":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"system"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/system","role":"symbol","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/system","type":"topic","kind":"symbol","title":"SourceErrorAttribute.system","abstract":[{"text":"Error caused by a system that the process runs on.","type":"text"},{"text":" ","type":"text"},{"text":"Hardware failure, OS-level error, resource exhaustion,","type":"text"},{"text":" ","type":"text"},{"text":"environment configuration, …","type":"text"}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/LocalizationErrorAttribute":{"type":"topic","url":"\/documentation\/swifterrorkit\/localizationerrorattribute","kind":"symbol","abstract":[{"type":"text","text":"An error attribute to provide a localized user message."}],"role":"symbol","navigatorTitle":[{"text":"LocalizationErrorAttribute","kind":"identifier"}],"title":"LocalizationErrorAttribute","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalizationErrorAttribute","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/LocalizationErrorAttribute"},"doc://SwiftErrorKit/SH":{"type":"unresolvable","identifier":"doc:\/\/SwiftErrorKit\/SH","title":"Swift.Hashable"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/DebugInfoErrorAttribute":{"title":"DebugInfoErrorAttribute","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DebugInfoErrorAttribute"}],"type":"topic","abstract":[{"text":"An error attribute to include custom debug info.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DebugInfoErrorAttribute","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/DebugInfoErrorAttribute","url":"\/documentation\/swifterrorkit\/debuginfoerrorattribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/input":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/input","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Error resulting from user interaction or input data problem."},{"type":"text","text":" "},{"text":"Invalid input data, form submission error, user request error, …","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"input","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/input","title":"SourceErrorAttribute.input"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/typeDescription":{"title":"typeDescription","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"typeDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/typeDescription","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/typedescription"},"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"type":"topic","role":"collection","abstract":[{"type":"text","text":"Error attribution and commons."}],"url":"\/documentation\/swifterrorkit","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","kind":"symbol","title":"SwiftErrorKit"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute","role":"symbol","navigatorTitle":[{"text":"SourceErrorAttribute","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An error attribute to include information about the high-level component"},{"text":" ","type":"text"},{"text":"in which the error emerged.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SourceErrorAttribute","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute","title":"SourceErrorAttribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/external":{"title":"SourceErrorAttribute.external","role":"symbol","type":"topic","abstract":[{"type":"text","text":"“Internal” error in external application."},{"type":"text","text":" "},{"type":"text","text":"Third-party API or service failure, unexpected behavior, …"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"external","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/external","url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/external"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/equatable-implementations","kind":"article","title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/Equatable-Implementations"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SeverityErrorAttribute":{"url":"\/documentation\/swifterrorkit\/severityerrorattribute","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SeverityErrorAttribute"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SeverityErrorAttribute","type":"topic","role":"symbol","abstract":[{"text":"An error attribute to express error severity in your system.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SeverityErrorAttribute"}],"title":"SeverityErrorAttribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/TagErrorAttribute":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TagErrorAttribute"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"TagErrorAttribute","kind":"identifier"}],"abstract":[{"text":"An error attribute to assign a tag to an error.","type":"text"}],"url":"\/documentation\/swifterrorkit\/tagerrorattribute","title":"TagErrorAttribute","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TagErrorAttribute"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/RankErrorAttribute":{"type":"topic","role":"symbol","url":"\/documentation\/swifterrorkit\/rankerrorattribute","title":"RankErrorAttribute","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RankErrorAttribute","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/RankErrorAttribute","navigatorTitle":[{"kind":"identifier","text":"RankErrorAttribute"}],"abstract":[{"type":"text","text":"An error attribute to assign a tracked issue a priority."}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/RawRepresentable-Implementations":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"kind":"article"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/init(rawValue:)":{"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/init(rawvalue:)","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/ErrorAttribute":{"type":"topic","title":"ErrorAttribute","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorAttribute","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorAttribute","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/ErrorAttribute","abstract":[{"type":"text","text":"A type that represents an error attribute."}],"url":"\/documentation\/swifterrorkit\/errorattribute","kind":"symbol"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/internal":{"role":"symbol","abstract":[{"type":"text","text":"Error in internal application."},{"type":"text","text":" "},{"type":"text","text":"Logic error, bug, or issue with internal operation, …"}],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/internal","title":"SourceErrorAttribute.internal","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/internal"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/SourceErrorAttribute/valueDescription":{"role":"symbol","abstract":[],"url":"\/documentation\/swifterrorkit\/sourceerrorattribute\/valuedescription","kind":"symbol","title":"valueDescription","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"valueDescription"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/SourceErrorAttribute\/valueDescription"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/TraceErrorAttribute":{"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/TraceErrorAttribute","kind":"symbol","abstract":[{"type":"text","text":"An error attribute to track a source location."}],"role":"symbol","url":"\/documentation\/swifterrorkit\/traceerrorattribute","title":"TraceErrorAttribute","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TraceErrorAttribute"}],"navigatorTitle":[{"text":"TraceErrorAttribute","kind":"identifier"}],"type":"topic"},"doc://SwiftErrorKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/SwiftErrorKit\/SQ","title":"Swift.Equatable"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/UserLevelErrorAttribute":{"type":"topic","url":"\/documentation\/swifterrorkit\/userlevelerrorattribute","title":"UserLevelErrorAttribute","kind":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/UserLevelErrorAttribute","navigatorTitle":[{"text":"UserLevelErrorAttribute","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserLevelErrorAttribute"}],"abstract":[{"type":"text","text":"An error attribute to express error level from user perspective."}]}}}