{"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"base"},{"kind":"text","text":": any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}],"extendedModule":"Swift","role":"symbol","externalID":"s:s5ErrorP05SwiftA3KitE4basesAA_pvp","title":"base","modules":[{"relatedModules":["Swift"],"name":"SwiftErrorKit"}],"symbolKind":"property","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error\/base","interfaceLanguage":"swift"},"abstract":[{"text":"Returns the original error. ","type":"text"},{"type":"codeVoice","code":"self"},{"text":" if ","type":"text"},{"type":"codeVoice","code":"self"},{"type":"text","text":" is the original error."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"base"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"aside","content":[{"inlineContent":[{"text":"Once you start using error attributes, you should expect vast majority of ","type":"text"},{"code":"any Error","type":"codeVoice"},{"type":"text","text":" values"},{"text":" ","type":"text"},{"type":"text","text":"to be "},{"inlineContent":[{"type":"text","text":"AttributedError"}],"type":"emphasis"},{"type":"text","text":". Everytime you need to work with the original error, you retrieve it"},{"text":" ","type":"text"},{"type":"text","text":"through this accessor."}],"type":"paragraph"}],"style":"important","name":"Important"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"You can find more info about the concept of ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"AttributedError.Base","type":"text"}]},{"type":"text","text":" in "},{"type":"reference","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/AttributedError","isActive":true},{"type":"text","text":"."}]}],"name":"See Also","style":"note"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swifterrorkit\/swift\/error\/base"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","seeAlsoSections":[{"title":"Another properties of AttributedError","identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error\/identifiable"],"generated":true}],"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"type":"topic","role":"collection","abstract":[{"type":"text","text":"Error attribution and commons."}],"url":"\/documentation\/swifterrorkit","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","kind":"symbol","title":"SwiftErrorKit"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/Swift/Error/base":{"role":"symbol","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error\/base","url":"\/documentation\/swifterrorkit\/swift\/error\/base","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"base"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"title":"base","abstract":[{"text":"Returns the original error. ","type":"text"},{"type":"codeVoice","code":"self"},{"type":"text","text":" if "},{"type":"codeVoice","code":"self"},{"type":"text","text":" is the original error."}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/Swift/Error":{"role":"symbol","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error"},{"type":"text","text":" extensions."}],"url":"\/documentation\/swifterrorkit\/swift\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error","kind":"symbol","type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"identifier"}],"title":"Error"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/AttributedError":{"kind":"article","abstract":[{"text":"Attribute errors using built-in attribute types, as well as your custom attributes.","type":"text"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/AttributedError","title":"Error attribution","type":"topic","role":"article","url":"\/documentation\/swifterrorkit\/attributederror"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/Swift/Error/identifiable":{"role":"symbol","abstract":[{"code":"base","type":"codeVoice"},{"text":" if the original error is ","type":"text"},{"type":"codeVoice","code":"Swift.Identifiable"},{"type":"text","text":", internal "},{"type":"emphasis","inlineContent":[{"text":"AttributedError","type":"text"}]},{"type":"text","text":" that is by default"},{"type":"text","text":" "},{"text":"an identified instance otherwise.","type":"text"}],"url":"\/documentation\/swifterrorkit\/swift\/error\/identifiable","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error\/identifiable","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifiable","kind":"identifier"},{"text":": any (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":" & "},{"text":"Identifiable","preciseIdentifier":"s:s12IdentifiableP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"identifiable"}}}