{"metadata":{"title":"identifiable","externalID":"s:s5ErrorP05SwiftA3KitE12identifiablesAA_s12Identifiablepvp","role":"symbol","modules":[{"name":"SwiftErrorKit","relatedModules":["Swift"]}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifiable","kind":"identifier"},{"kind":"text","text":": any ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"Identifiable","preciseIdentifier":"s:s12IdentifiableP"},{"text":")","kind":"text"}],"extendedModule":"Swift","symbolKind":"property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error\/base"],"title":"Another properties of AttributedError","generated":true}],"variants":[{"paths":["\/documentation\/swifterrorkit\/swift\/error\/identifiable"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error"]]},"identifier":{"url":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error\/identifiable","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"codeVoice","code":"base"},{"type":"text","text":" if the original error is "},{"code":"Swift.Identifiable","type":"codeVoice"},{"text":", internal ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"AttributedError"}]},{"text":" that is by default","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"an identified instance otherwise."}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifiable"},{"kind":"text","text":": any ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":" & ","kind":"text"},{"text":"Identifiable","kind":"typeIdentifier","preciseIdentifier":"s:s12IdentifiableP"},{"text":") { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the original error doesnâ€™t conform to "},{"type":"codeVoice","code":"Swift.Identifiable"},{"text":", the ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"AttributedError"}]},{"text":" identifies","type":"text"},{"type":"text","text":" "},{"text":"the instance with a generated ","type":"text"},{"type":"codeVoice","code":"Foundation.UUID"},{"text":". You can use this value to track error instances.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example, you could provide the error ID to the user, so you can locate the exact error they"},{"type":"text","text":" "},{"type":"text","text":"encountered in your monitoring system."}]},{"type":"paragraph","inlineContent":[{"code":"let errorID = anyError.identifiable.id","type":"codeVoice"}]},{"content":[{"inlineContent":[{"text":"You can find more info about the concept of ","type":"text"},{"inlineContent":[{"text":"AttributedError.ID","type":"text"}],"type":"emphasis"},{"type":"text","text":" in "},{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/AttributedError"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"See Also","style":"note","type":"aside"},{"type":"aside","content":[{"inlineContent":[{"text":"Provide ","type":"text"},{"type":"codeVoice","code":"Swift.Identifiable"},{"type":"text","text":" generator middleware so clients can set their preffered"},{"text":" ","type":"text"},{"type":"text","text":"default "},{"code":"ID","type":"codeVoice"},{"text":" type. This would also lift depencency on ","type":"text"},{"type":"codeVoice","code":"Foundation"}],"type":"paragraph"}],"name":"To Do","style":"note"}]}],"references":{"doc://SwiftErrorKit/documentation/SwiftErrorKit":{"abstract":[{"type":"text","text":"Error attribution and commons."}],"url":"\/documentation\/swifterrorkit","type":"topic","title":"SwiftErrorKit","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit","kind":"symbol","role":"collection"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/Swift/Error/base":{"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error\/base","url":"\/documentation\/swifterrorkit\/swift\/error\/base","title":"base","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"base"},{"text":": any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}],"kind":"symbol","type":"topic","abstract":[{"text":"Returns the original error. ","type":"text"},{"type":"codeVoice","code":"self"},{"text":" if ","type":"text"},{"type":"codeVoice","code":"self"},{"type":"text","text":" is the original error."}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/AttributedError":{"title":"Error attribution","type":"topic","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/AttributedError","role":"article","abstract":[{"type":"text","text":"Attribute errors using built-in attribute types, as well as your custom attributes."}],"kind":"article","url":"\/documentation\/swifterrorkit\/attributederror"},"doc://SwiftErrorKit/documentation/SwiftErrorKit/Swift/Error/identifiable":{"role":"symbol","url":"\/documentation\/swifterrorkit\/swift\/error\/identifiable","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifiable"},{"kind":"text","text":": any ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":" & ","kind":"text"},{"preciseIdentifier":"s:s12IdentifiableP","text":"Identifiable","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error\/identifiable","title":"identifiable","abstract":[{"code":"base","type":"codeVoice"},{"text":" if the original error is ","type":"text"},{"type":"codeVoice","code":"Swift.Identifiable"},{"type":"text","text":", internal "},{"inlineContent":[{"text":"AttributedError","type":"text"}],"type":"emphasis"},{"type":"text","text":" that is by default"},{"text":" ","type":"text"},{"type":"text","text":"an identified instance otherwise."}]},"doc://SwiftErrorKit/documentation/SwiftErrorKit/Swift/Error":{"title":"Error","fragments":[{"kind":"keyword","text":"extension"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error","url":"\/documentation\/swifterrorkit\/swift\/error","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftErrorKit\/documentation\/SwiftErrorKit\/Swift\/Error"},{"text":" extensions.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic"}}}